# -*- coding: utf-8 -*-
"""armstrong numbers coded.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LGVl7__I62s7WxHqB31iqhwKhzLVMxIR
"""

def checker(number):
  arm = 0
  str_num = str(number)
  length = len(str_num)
  for i in range(length):
    digit = int(str_num[i])
    arm = arm+ digit**length
  if int(number) == int(arm):
    return print("It is an armstrong number",arm)
  else:
    return print("Not an armstrong number",arm)

entries = int(input("number of tries"))
numbers={}
for ent in range(entries):
  numbers[ent]= int(input("enter the number"))
for value in numbers.values():
  checker(value)

